module.exports = async function ({github, context}) {
	const tagPattern = /v\d+\.\d+\.\d+/
	const goPlatformClientVersion = require('fs')
		.readFileSync('clients.go', 'utf8')
		.match(tagPattern)
	if (!goPlatformClientVersion) {
		console.log('No version for Go platform client found in clients.go\n',
		            'Looked for pattern: ' + tagPattern + '\n',
		            'Debug: A semver version (i.e. v1.2.3) is expected to be' +
			            ' declared as a constant (`const Version =' +
			            ' "v.1.2.3"`) near the top of the clients.go file.' +
			            ' This correlates to the platform client version' +
			            ' generated by theGrpcClientsGenerator.\n\n',
		            'Skipping tag creation')
		return
	}
	console.log('Found Go platform client version: ' + goPlatformClientVersion)
	
	const response = await github.rest.repos.listTags(
		{
			owner: context.repo.owner,
			repo: context.repo.repo,
			pattern: tagPattern
		}
	)
	
	for (const tag of response.data) {
		if (goPlatformClientVersion === tag.name) {
			console.log('Tag ' + goPlatformClientVersion +
				            ' already exists\n\n',
			            `Debug: Tags found for this repo:
			            ${response.data.map((tag) => tag.name)}\n\n`,
			            'Skipping tag creation')
			
			return
		}
	}
	
	github.rest.git.createRef(
			{
				owner: context.repo.owner,
				repo: context.repo.repo,
				ref: `refs/tags/${goPlatformClientVersion}`,
				sha: context.sha
			})
		.then(() => console.log("Tag " + goPlatformClientVersion + " created"))
		.catch((error) => console.log(error))
}
