name: update tags
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'go.mod'
      - 'clients.go'
      - 'src/Grpc/Services/Mercari/Platform/Apius/**'
permissions:
  contents: write
jobs:
  update-grpc-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update gRPC Tags
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./tool/github-script/update-grpc-tags.js')
            await script({ context, github })
