name: update tag
on:
  push:
    branches:
      - main
      - master
permissions:
  contents: write
jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Tag
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./tool/github-script/update-tag/update-tag.js')
            await script({ context, github })
