name: update tag
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'clients.go'
permissions:
  contents: write
jobs:
    update-tag:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Update Tag
              uses: actions/github-script@v6
              with:
                script: |
                  const script = require('./script/update-tag.js')
                  await script({ context, github })